# Generated by Django 4.2.6 on 2024-01-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_notes_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
