# Generated by Django 4.2.6 on 2024-01-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('by', models.CharField(max_length=255)),
                ('notes_file', models.FileField(upload_to='notes/')),
            ],
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
