# Generated by Django 4.2.6 on 2024-02-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_note_delete_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
