# Generated by Django 4.2.6 on 2024-03-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_course_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
