# Generated by Django 4.2.6 on 2024-03-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_rename_notes_note_rename_topic_note_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='topic',
        ),
        migrations.AlterField(
            model_name='note',
            name='notes_file',
            field=models.FileField(upload_to=''),
        ),
    ]
